name: Flutter CI

on:
  push:
    branches:
      - main
      - ci/github-actions
      - feat/detecta-codigo-deprecado
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Detectar código depreciado
        run: |
          flutter analyze 2>&1 | tee analyze.log
          if grep -q "deprecated_member_use" analyze.log; then
            echo "Código depreciado encontrado."
            exit 1
          fi
          echo "Nenhum código depreciado encontrado."

      - name: Gerar build
        run: flutter build apk --debug
